# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md 

pr:  
  autoCancel: true
  branches:
    include:
      - '*'
  paths:
    exclude:
      - README.md

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    codeCoverageSourceDirectories: 'controller/TaskControllerTest.java,taskbackend/DataUtilsTest.java'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package verify'
    codeCoverageToolOption: JaCoCo

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/target/site/jacoco'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'JUnit Test Results'
    searchFolder: '$(System.DefaultWorkingDirectory)'

